version: '3.8'

services:
  nebula-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/nebula-sports
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: sleep infinity
    networks:
      - nebula-network

networks:
  nebula-network:
    driver: bridge
